// This file has been generated by the reflectable package.
// https://github.com/dart-lang/reflectable.
// @dart = 2.12

import 'dart:core';
import 'main.dart' as prefix1;
import 'package:first_project/202/cache/secure_storage/secure_storage_learn.dart'
    as prefix2;
import 'package:first_project/202/reflection/reflection_helper.dart' as prefix0;

// ignore_for_file: camel_case_types
// ignore_for_file: implementation_imports
// ignore_for_file: prefer_adjacent_string_concatenation
// ignore_for_file: prefer_collection_literals
// ignore_for_file: unnecessary_const

// ignore:unused_import
import 'package:reflectable/mirrors.dart' as m;
// ignore:unused_import
import 'package:reflectable/src/reflectable_builder_based.dart' as r;
// ignore:unused_import
import 'package:reflectable/reflectable.dart' as r show Reflectable;

final _data = <r.Reflectable, r.ReflectorData>{
  const prefix0.Reflector(): r.ReflectorData(
      <m.TypeMirror>[
        r.NonGenericClassMirrorImpl(
            r'Product',
            r'.Product',
            134217735,
            0,
            const prefix0.Reflector(),
            const <int>[0, 1, 4, 9],
            const <int>[10, 4, 11, 12, 13, 5, 6, 7, 8],
            const <int>[],
            -1,
            {},
            {},
            {r'': (bool b) => () => b ? prefix1.Product() : null},
            -1,
            0,
            const <int>[],
            null,
            null),
        r.NonGenericClassMirrorImpl(
            r'Product',
            r'.Product',
            134217735,
            1,
            const prefix0.Reflector(),
            const <int>[2, 3, 14, 19],
            const <int>[10, 14, 11, 12, 13, 15, 16, 17, 18],
            const <int>[],
            -1,
            {},
            {},
            {r'': (bool b) => () => b ? prefix2.Product() : null},
            -1,
            1,
            const <int>[],
            null,
            null)
      ],
      <m.DeclarationMirror>[
        r.VariableMirrorImpl(r'name', 67239941, 0, const prefix0.Reflector(),
            -1, 2, 2, const <int>[], null),
        r.VariableMirrorImpl(r'desc', 67239941, 0, const prefix0.Reflector(),
            -1, 2, 2, const <int>[], null),
        r.VariableMirrorImpl(r'name', 67239941, 1, const prefix0.Reflector(),
            -1, 2, 2, const <int>[], null),
        r.VariableMirrorImpl(r'desc', 67239941, 1, const prefix0.Reflector(),
            -1, 2, 2, const <int>[], null),
        r.MethodMirrorImpl(r'toString', 2097154, 0, -1, 3, 3, const <int>[],
            const <int>[], const prefix0.Reflector(), null),
        r.ImplicitGetterMirrorImpl(const prefix0.Reflector(), 0, 5),
        r.ImplicitSetterMirrorImpl(const prefix0.Reflector(), 0, 6),
        r.ImplicitGetterMirrorImpl(const prefix0.Reflector(), 1, 7),
        r.ImplicitSetterMirrorImpl(const prefix0.Reflector(), 1, 8),
        r.MethodMirrorImpl(r'', 64, 0, -1, 0, 0, const <int>[], const <int>[],
            const prefix0.Reflector(), null),
        r.MethodMirrorImpl(r'==', 2097154, -1, -1, 4, 4, const <int>[],
            const <int>[2], const prefix0.Reflector(), null),
        r.MethodMirrorImpl(r'noSuchMethod', 524290, -1, -1, -1, -1,
            const <int>[], const <int>[3], const prefix0.Reflector(), null),
        r.MethodMirrorImpl(r'hashCode', 2097155, -1, -1, 5, 5, const <int>[],
            const <int>[], const prefix0.Reflector(), null),
        r.MethodMirrorImpl(r'runtimeType', 2097155, -1, -1, 6, 6, const <int>[],
            const <int>[], const prefix0.Reflector(), null),
        r.MethodMirrorImpl(r'toString', 2097154, 1, -1, 3, 3, const <int>[],
            const <int>[], const prefix0.Reflector(), null),
        r.ImplicitGetterMirrorImpl(const prefix0.Reflector(), 2, 15),
        r.ImplicitSetterMirrorImpl(const prefix0.Reflector(), 2, 16),
        r.ImplicitGetterMirrorImpl(const prefix0.Reflector(), 3, 17),
        r.ImplicitSetterMirrorImpl(const prefix0.Reflector(), 3, 18),
        r.MethodMirrorImpl(r'', 64, 1, -1, 1, 1, const <int>[], const <int>[],
            const prefix0.Reflector(), null)
      ],
      <m.ParameterMirror>[
        r.ParameterMirrorImpl(r'_name', 67240038, 6, const prefix0.Reflector(),
            -1, 2, 2, const <int>[], null, null, null),
        r.ParameterMirrorImpl(r'_desc', 67240038, 8, const prefix0.Reflector(),
            -1, 2, 2, const <int>[], null, null, null),
        r.ParameterMirrorImpl(
            r'other',
            134348806,
            10,
            const prefix0.Reflector(),
            -1,
            7,
            7,
            const <int>[],
            null,
            null,
            null),
        r.ParameterMirrorImpl(
            r'invocation',
            134348806,
            11,
            const prefix0.Reflector(),
            -1,
            8,
            8,
            const <int>[],
            null,
            null,
            null),
        r.ParameterMirrorImpl(r'_name', 67240038, 16, const prefix0.Reflector(),
            -1, 2, 2, const <int>[], null, null, null),
        r.ParameterMirrorImpl(r'_desc', 67240038, 18, const prefix0.Reflector(),
            -1, 2, 2, const <int>[], null, null, null)
      ],
      <Type>[
        prefix1.Product,
        prefix2.Product,
        String,
        String,
        bool,
        int,
        Type,
        Object,
        Invocation
      ],
      2,
      {
        r'==': (dynamic instance) => (x) => instance == x,
        r'toString': (dynamic instance) => instance.toString,
        r'noSuchMethod': (dynamic instance) => instance.noSuchMethod,
        r'hashCode': (dynamic instance) => instance.hashCode,
        r'runtimeType': (dynamic instance) => instance.runtimeType,
        r'name': (dynamic instance) => instance.name,
        r'desc': (dynamic instance) => instance.desc
      },
      {
        r'name=': (dynamic instance, value) => instance.name = value,
        r'desc=': (dynamic instance, value) => instance.desc = value
      },
      null,
      [])
};

final _memberSymbolMap = null;

void initializeReflectable() {
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
